chore(deps): update dependency knip to v5.34.0 (#811)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [knip](https://knip.dev)
([source](https://redirect.github.com/webpro-nl/knip/tree/HEAD/packages/knip))
| [`5.30.5` ->
`5.34.0`](https://renovatebot.com/diffs/npm/knip/5.30.5/5.34.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/knip/5.34.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/knip/5.34.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/knip/5.30.5/5.34.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/knip/5.30.5/5.34.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>webpro-nl/knip (knip)</summary>

###
[`v5.34.0`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.34.0)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.33.3...5.34.0)

- Don't use `path` if step also has `repository` in github-action plugin
([`c6e4d31`](https://redirect.github.com/webpro-nl/knip/commit/c6e4d310))
- Give plugins a chance to prep config args
([`a2217a2`](https://redirect.github.com/webpro-nl/knip/commit/a2217a28))
- Let's start out conservatively
([`a2e83f8`](https://redirect.github.com/webpro-nl/knip/commit/a2e83f88))
- More consistent naming
([`bae87d9`](https://redirect.github.com/webpro-nl/knip/commit/bae87d96))
- Optimize a bit after the dust has settled
([`31f1e7e`](https://redirect.github.com/webpro-nl/knip/commit/31f1e7ee))
- Cherry on the pie
([`617e067`](https://redirect.github.com/webpro-nl/knip/commit/617e067e))
- Handle config files only once across workspaces
([`939f511`](https://redirect.github.com/webpro-nl/knip/commit/939f5110))
- Improve naming and simplify a few things
([`f4db204`](https://redirect.github.com/webpro-nl/knip/commit/f4db2047))
- Add coverage for unused files with compiler extension
([`c2e2712`](https://redirect.github.com/webpro-nl/knip/commit/c2e27127))
- Ignore `virtual:` imports, don't report as unlisted dependencies
([`2ef75cc`](https://redirect.github.com/webpro-nl/knip/commit/2ef75ccf))
- Remove module resolving from plugins
([`53839e0`](https://redirect.github.com/webpro-nl/knip/commit/53839e08))
- Temp use Bun for in this integration test for green lights
([`98c1ff7`](https://redirect.github.com/webpro-nl/knip/commit/98c1ff7a))
- Add ability to add unresolved imports to `ignoreDependencies`
([`b8875be`](https://redirect.github.com/webpro-nl/knip/commit/b8875be3))
- Let's start out a tad more conservative
([`58ba79f`](https://redirect.github.com/webpro-nl/knip/commit/58ba79f9))
- Update dependencies
([`f4dc1e1`](https://redirect.github.com/webpro-nl/knip/commit/f4dc1e11))
- Optimize referenced dependency handling
([`a413ad8`](https://redirect.github.com/webpro-nl/knip/commit/a413ad84))
- Resolve config file paths and parse recursively
([`c03f963`](https://redirect.github.com/webpro-nl/knip/commit/c03f9630))
- Exclude empty config file path arrays from debug output
([`d288779`](https://redirect.github.com/webpro-nl/knip/commit/d288779e))
- Extend typedoc plugin
([`f2732fa`](https://redirect.github.com/webpro-nl/knip/commit/f2732fad))
- Presets are extended by local config in jest plugin
([`4973a9d`](https://redirect.github.com/webpro-nl/knip/commit/4973a9dc))
- Add test case to get refs from scripts
([`6115107`](https://redirect.github.com/webpro-nl/knip/commit/61151070))
- Refactor binary resolver & referenced dependency handling
([`f1349c2`](https://redirect.github.com/webpro-nl/knip/commit/f1349c23))

###
[`v5.33.3`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.33.3)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.33.2...5.33.3)

- Add comment (close
[#&#8203;808](https://redirect.github.com/webpro-nl/knip/issues/808))
([`3dd6cfd`](https://redirect.github.com/webpro-nl/knip/commit/3dd6cfd0))
- Don't remove internally referenced bindingElement nodes
([#&#8203;808](https://redirect.github.com/webpro-nl/knip/issues/808))
([`307ef8d`](https://redirect.github.com/webpro-nl/knip/commit/307ef8df))
- Expand unused exports referenced in used exports
([#&#8203;808](https://redirect.github.com/webpro-nl/knip/issues/808))
([`1c04163`](https://redirect.github.com/webpro-nl/knip/commit/1c041635))
- Got tired of it
([`2f2a11e`](https://redirect.github.com/webpro-nl/knip/commit/2f2a11ea))
- Add test in new workspaces fixture for
[`3ee0476`](https://redirect.github.com/webpro-nl/knip/commit/3ee04761)
([`4a3f84c`](https://redirect.github.com/webpro-nl/knip/commit/4a3f84cd))
- Fix travis `isEnabled`
([`b6541f3`](https://redirect.github.com/webpro-nl/knip/commit/b6541f32))

###
[`v5.33.2`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.33.2)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.33.1...5.33.2)

- Revert "Add/fix `getPluginEntryFilePatterns` helper" (resolves
[#&#8203;804](https://redirect.github.com/webpro-nl/knip/issues/804))
([`3ee0476`](https://redirect.github.com/webpro-nl/knip/commit/3ee04761))
- Add French article + order by date (recent first)
([`617a06a`](https://redirect.github.com/webpro-nl/knip/commit/617a06a1))
- Skip windows-latest (error: "The syntax of the command is incorrect")
([`aebbfb6`](https://redirect.github.com/webpro-nl/knip/commit/aebbfb64))

###
[`v5.33.1`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.33.1)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.33.0...5.33.1)

- Upgrade jiti
([`a056e8d`](https://redirect.github.com/webpro-nl/knip/commit/a056e8d9))

###
[`v5.33.0`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.33.0)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.32.0...5.33.0)

- Remove more whitespace including newlines with enum members
([`29b35ea`](https://redirect.github.com/webpro-nl/knip/commit/29b35ea7))
- Upgrade jiti to v2.3.2
([`c5b94c9`](https://redirect.github.com/webpro-nl/knip/commit/c5b94c91))
- Add `module` and `browser` fields to `getEntryPathsFromManifest`
([`e63ebec`](https://redirect.github.com/webpro-nl/knip/commit/e63ebeca))

###
[`v5.32.0`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.32.0)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.31.0...5.32.0)

- Add `pos` to reference pragma import node
([`f704a2b`](https://redirect.github.com/webpro-nl/knip/commit/f704a2bb))
- Rename propertyAccessCall → resolveCall
([`72b4827`](https://redirect.github.com/webpro-nl/knip/commit/72b48273))
- Update dev doc
([`36b85ba`](https://redirect.github.com/webpro-nl/knip/commit/36b85bad))
- Minor refactor, add comments to get-imports-and-exports
([`e9416ec`](https://redirect.github.com/webpro-nl/knip/commit/e9416ec5))
- Add `ts.isPropertyAssignment` to `isConsiderReferencedNS`
([`e4bada4`](https://redirect.github.com/webpro-nl/knip/commit/e4bada42))
- Use `{default: true}` in jiti.import call
([`700a091`](https://redirect.github.com/webpro-nl/knip/commit/700a091c))
- Update a few dependencies
([`d2a7b59`](https://redirect.github.com/webpro-nl/knip/commit/d2a7b597))
- Consider enum members used if used in object enumeration method
(resolves
[#&#8203;699](https://redirect.github.com/webpro-nl/knip/issues/699))
([`feab792`](https://redirect.github.com/webpro-nl/knip/commit/feab7921))
- Refactor behavior with/out ignoreExportsUsedInFile
([`14d2cfc`](https://redirect.github.com/webpro-nl/knip/commit/14d2cfc2))
- Always check types/classes for referenced in exported type
([`50bc125`](https://redirect.github.com/webpro-nl/knip/commit/50bc1256))
- Don't try to find refs to empty string in `findInternalReferences`
([`42d626f`](https://redirect.github.com/webpro-nl/knip/commit/42d626f9))
- Don't ignore (global) dependency if relative path
([`86ec088`](https://redirect.github.com/webpro-nl/knip/commit/86ec088d))
- Move hard-coded `deno` out of bash parser
([`fb0da5b`](https://redirect.github.com/webpro-nl/knip/commit/fb0da5b7))
- Add travis CI plugin
([`4821b52`](https://redirect.github.com/webpro-nl/knip/commit/4821b528))
- Improve nyc plugin
([`e6fa86a`](https://redirect.github.com/webpro-nl/knip/commit/e6fa86ac))
- Stylelint plugin - fix issue where "customSyntax" property is not
recognised as a resolved dependency
([#&#8203;802](https://redirect.github.com/webpro-nl/knip/issues/802))
([`fdb0246`](https://redirect.github.com/webpro-nl/knip/commit/fdb02462))
- Don't try to find refs to empty string in `findInternalReferences`
(fixes
[#&#8203;800](https://redirect.github.com/webpro-nl/knip/issues/800))
([`d9ae5dc`](https://redirect.github.com/webpro-nl/knip/commit/d9ae5dc9))
- Update docs
([`0749921`](https://redirect.github.com/webpro-nl/knip/commit/0749921b))
- Post "two years"
([`69c021b`](https://redirect.github.com/webpro-nl/knip/commit/69c021b2))

###
[`v5.31.0`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.31.0)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.30.6...5.31.0)

- Do not treat trailing `#` in gitignore as comment
([#&#8203;797](https://redirect.github.com/webpro-nl/knip/issues/797))
([`7fc6355`](https://redirect.github.com/webpro-nl/knip/commit/7fc63552))
- Fix extension for file fixture containing TS
([`847649d`](https://redirect.github.com/webpro-nl/knip/commit/847649df))
- Update some devDependencies
([`d304d8d`](https://redirect.github.com/webpro-nl/knip/commit/d304d8db))
- Update docs for auto-fix (close
[#&#8203;788](https://redirect.github.com/webpro-nl/knip/issues/788))
([`48fbddf`](https://redirect.github.com/webpro-nl/knip/commit/48fbddfd))
- Consistent reporter output
([`94da7f7`](https://redirect.github.com/webpro-nl/knip/commit/94da7f78))
- Add support for enum and class members
([`1109cbf`](https://redirect.github.com/webpro-nl/knip/commit/1109cbf6))
- Refactor for reuse/readabilty, more tests
([`20c2390`](https://redirect.github.com/webpro-nl/knip/commit/20c2390c))
- Fix issue type in export declarations
([`0f786f4`](https://redirect.github.com/webpro-nl/knip/commit/0f786f4b))
- Support exported types
([`2a251fa`](https://redirect.github.com/webpro-nl/knip/commit/2a251fa2))
- Improve unused export fixer, add tests
([`b0bb643`](https://redirect.github.com/webpro-nl/knip/commit/b0bb6430))
- Update docs
([`b384403`](https://redirect.github.com/webpro-nl/knip/commit/b384403c))
- Improve var naming in tests
([`2ed9e51`](https://redirect.github.com/webpro-nl/knip/commit/2ed9e514))
- Upgrade to jiti v2.1.0
([`dea12f8`](https://redirect.github.com/webpro-nl/knip/commit/dea12f81))
- Update docs re. known issues w/ jiti
([`6819eb9`](https://redirect.github.com/webpro-nl/knip/commit/6819eb93))
- Remove obsolete jiti options
([`6d47630`](https://redirect.github.com/webpro-nl/knip/commit/6d476308))
- Use jiti.import + add tests (resolves
[#&#8203;565](https://redirect.github.com/webpro-nl/knip/issues/565))
([`3dd8ea6`](https://redirect.github.com/webpro-nl/knip/commit/3dd8ea68))
- Migrate to jiti v2
([`de7fa2d`](https://redirect.github.com/webpro-nl/knip/commit/de7fa2d4))

###
[`v5.30.6`](https://redirect.github.com/webpro-nl/knip/releases/tag/5.30.6)

[Compare
Source](https://redirect.github.com/webpro-nl/knip/compare/5.30.5...5.30.6)

- Ignore TS issue with Bun for now
([`2a36139`](https://redirect.github.com/webpro-nl/knip/commit/2a361399))
- Add --trace arguments to help text
([`4b314e2`](https://redirect.github.com/webpro-nl/knip/commit/4b314e2a))
- accept \_ and . in package names
([#&#8203;790](https://redirect.github.com/webpro-nl/knip/issues/790))
([`84db245`](https://redirect.github.com/webpro-nl/knip/commit/84db2459))
- Remove duplicate job (it's in integration.yml as well)
([`2b550b0`](https://redirect.github.com/webpro-nl/knip/commit/2b550b0f))
- continue-on-error: true → fail-fast: false
([`8ed9314`](https://redirect.github.com/webpro-nl/knip/commit/8ed9314c))
- Update argos ci commands
([`ed4bad2`](https://redirect.github.com/webpro-nl/knip/commit/ed4bad21))
- Add freeCodeCamp to integration suite
([`0784ca5`](https://redirect.github.com/webpro-nl/knip/commit/0784ca5f))
- Update FUNDING.yml
([`cf6c5fe`](https://redirect.github.com/webpro-nl/knip/commit/cf6c5fe8))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/JoshuaKGoldberg/console-fail-test).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOC45Ny4wIiwidXBkYXRlZEluVmVyIjoiMzguMTIwLjEiLCJ0YXJnZXRCcmFuY2giOiJtYWluIiwibGFiZWxzIjpbImRlcGVuZGVuY2llcyJdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>